package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"moleAgent_Serv/internal/api"
	"moleAgent_Serv/internal/auth"
	"moleAgent_Serv/internal/config"
	"moleAgent_Serv/internal/core"
	"moleAgent_Serv/internal/crypto"
	"moleAgent_Serv/internal/dingtalk"
	"moleAgent_Serv/internal/feishu"
	"moleAgent_Serv/internal/logging"
	"moleAgent_Serv/internal/mqtt"
	"moleAgent_Serv/internal/node"
	"moleAgent_Serv/internal/ratelimit"
	"moleAgent_Serv/internal/service"
	"moleAgent_Serv/internal/storage"
	"moleAgent_Serv/internal/tunnel"
	"moleAgent_Serv/internal/version"
)

func main() {
	configPath := flag.String("config", "", "配置文件路径 (YAML)，默认查找顺序: config.yaml → configs/config.yaml")
	nodeToken := flag.String("nodetoken", "", "节点认证令牌")
	verFlag := flag.Bool("version", false, "打印版本信息并退出")
	flag.Parse()
	if *verFlag {
		fmt.Println(version.VersionString())
		os.Exit(0)
	}

	slog.Info("Starting moleAgent-Serv", "version", version.VersionString())

	// 确定配置文件路径：命令行 > config.yaml > configs/config.yaml > 无配置启动
	resolved := *configPath
	if resolved == "" {
		if _, err := os.Stat("config.yaml"); err == nil {
			resolved = "config.yaml"
		} else if _, err := os.Stat("configs/config.yaml"); err == nil {
			resolved = "configs/config.yaml"
		}
	}

	// 加载配置
	cfg, err := config.Load(resolved)
	if err != nil {
		slog.Error("Failed to load config", "error", err)
		os.Exit(1)
	}

	// 初始化日志
	logging.Init(cfg.Logging)

	slog.Info("moleAgent_Serv starting...")

	// 初始化隧道凭证加密器
	// 仅当存在「用户显式配置的稳定 secret」时才启用加密。若唯一可用的 secret 是
	// 每次启动随机生成的 JWTSecret，则禁用加密（明文存储）——用随机 key 加密持久化
	// 数据会导致重启后凭证永久损坏，且静默下发无法解密的密文给客户端。
	var tunnelEncryptor *crypto.SecretEncryptor
	switch {
	case cfg.Auth.TunnelSecret != "":
		// 用户显式配置了专用隧道密钥
		tunnelEncryptor, err = crypto.NewSecretEncryptor(cfg.Auth.TunnelSecret)
	case !cfg.JWTSecretAutoGenerated():
		// 未配 tunnel_secret，但 JWTSecret 是用户显式配置的稳定值，可复用
		tunnelEncryptor, err = crypto.NewSecretEncryptor(cfg.Auth.JWTSecret)
	default:
		// JWTSecret 为本次启动自动生成，不可用于加密持久化数据
		slog.Warn("隧道凭证加密已禁用：auth.tunnel_secret 为空且 jwt_secret 为本次启动自动生成；webssh 凭证将以明文存储。如需加密请显式配置 auth.tunnel_secret 或 auth.jwt_secret")
	}
	if err != nil {
		slog.Error("Failed to init tunnel encryptor", "error", err)
		os.Exit(1)
	}

	// 初始化数据库
	if err := storage.Init(cfg.Database); err != nil {
		slog.Error("Failed to init database", "error", err)
		os.Exit(1)
	}
	defer storage.Close()

	// 优雅关闭
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		sig := <-sigCh
		slog.Info("Received signal, shutting down...", "signal", sig.String())
		cancel()
	}()

	// --- 依赖注入 ---
	db := storage.DB()
	userRepo := storage.NewUserRepo(db)
	roleRepo := storage.NewRoleRepo(db)

	jwtMgr := auth.NewJWTManager(cfg.Auth.JWTSecret, parseExpiry(cfg.Auth.JWTExpiry))
	rbacEngine := auth.NewRBACEngine(db, roleRepo)
	authSvc := auth.NewAuthService(jwtMgr, userRepo, roleRepo, rbacEngine, db)
	authMW := auth.NewAuthMiddleware(jwtMgr, rbacEngine, func() string {
		return storage.GetGlobalAccessKey()
	})

	// API rate limiter (nil when disabled)
	var apiLimiter *ratelimit.APILimiter
	if cfg.RateLimit.API.Enabled {
		jwtVerify := ratelimit.JWTVerifierFunc(func(tokenString string) (string, bool) {
			claims, err := jwtMgr.VerifyToken(tokenString)
			if err != nil {
				return "", false
			}
			return claims.UserID, true
		})
		apiLimiter = ratelimit.NewAPILimiter(cfg.RateLimit.API, jwtVerify)
	}

	nodeMgr := node.NewShardedNodeManager(256)
	nodeRepo := storage.NewNodeRepo(db)

	// --- 网关服务（HTTP 隧道）---（在 controlSrv 之前创建，因为注册回调需要引用）
	// Gateway rate limiter (NopLimiter when disabled)
	var gatewayLimiter ratelimit.GatewayLimiter
	if cfg.RateLimit.Gateway.Enabled {
		gatewayLimiter = ratelimit.NewGatewayLimiter(cfg.RateLimit.Gateway)
		slog.Info("Gateway rate limiting enabled",
			"maxConnsPerNode", cfg.RateLimit.Gateway.MaxConnsPerNode,
			"maxConnsPerTunnel", cfg.RateLimit.Gateway.MaxConnsPerTunnel,
			"maxBandwidth", cfg.RateLimit.Gateway.MaxBandwidthPerTunnel,
		)
	}

	gateway := tunnel.NewTunnelGateway(nodeMgr, cfg.Server.MaxConcurrent, gatewayLimiter)
	gateway.HyphenRouting = cfg.Server.Gateway.HyphenRouting

	// --- 控制端口 ---
	token := *nodeToken
	if token == "" {
		token = os.Getenv("MA_NODE_TOKEN")
	}
	if token == "" {
		token = "default-node-token-change-me"
	}
	var tlsConfig *tls.Config
	if cfg.Server.TLS.Enabled {
		cert, err := tls.LoadX509KeyPair(cfg.Server.TLS.CertFile, cfg.Server.TLS.KeyFile)
		if err != nil {
			slog.Error("Failed to load TLS certificate", "error", err)
			os.Exit(1)
		}
		tlsConfig = &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
		}
	}
	// --- 选择传输协议 ---
	var transport tunnel.Transport
	switch cfg.Server.Transport {
	case "ws":
		transport = tunnel.NewWSTransport(tlsConfig)
	case "kcp":
		kcpCfg := tunnel.KCPConfig{
			Key:          cfg.Server.KCP.Key,
			DataShards:   cfg.Server.KCP.DataShards,
			ParityShards: cfg.Server.KCP.ParityShards,
			NoDelay:      cfg.Server.KCP.NoDelay,
			Interval:     cfg.Server.KCP.Interval,
			Resend:       cfg.Server.KCP.Resend,
			NoCongestion: cfg.Server.KCP.NoCongestion,
			SendWindow:   cfg.Server.KCP.SendWindow,
			RecvWindow:   cfg.Server.KCP.RecvWindow,
		}
		transport = tunnel.NewKCPTransport(kcpCfg)
	default:
		transport = tunnel.NewTCPTransport(tlsConfig)
	}
	controlSrv := tunnel.NewControlServer(cfg.Server.ControlPort, transport, nodeMgr, token, nodeRepo)

	// 额外传输层：WS、KCP 可与 TCP 同时监听
	if cfg.Server.WSPort != "" {
		controlSrv.AddTransport(cfg.Server.WSPort, tunnel.NewWSTransport(tlsConfig))
	}
	if cfg.Server.KCPPort != "" {
		controlSrv.AddTransport(cfg.Server.KCPPort, tunnel.NewKCPTransport(tunnel.KCPConfig{
			Key:          cfg.Server.KCP.Key,
			DataShards:   cfg.Server.KCP.DataShards,
			ParityShards: cfg.Server.KCP.ParityShards,
			NoDelay:      cfg.Server.KCP.NoDelay,
			Interval:     cfg.Server.KCP.Interval,
			Resend:       cfg.Server.KCP.Resend,
			NoCongestion: cfg.Server.KCP.NoCongestion,
			SendWindow:   cfg.Server.KCP.SendWindow,
			RecvWindow:   cfg.Server.KCP.RecvWindow,
		}))
	}
	controlSrv.SetOnNodeChange(func() {
		gateway.RebuildIndex(context.Background())
	})
	go func() {
		if err := controlSrv.Start(ctx); err != nil {
			slog.Error("Control server error", "error", err)
			cancel()
		}
	}()

	// --- 隧道配置服务（单一变更入口）---
	tunnelSvc := service.NewTunnelConfigService(ctx, nodeMgr, nodeRepo, gateway, controlSrv, gatewayLimiter, tunnelEncryptor)
	controlSrv.SetTunnelConfigManager(tunnelSvc)

	// --- 节点断开回调：清理隧道运行时资源（监听器、路由索引、统计）---
	disconnectHandler := func(nodeID string, tunnels []core.Tunnel) {
		tunnelSvc.ReleaseNodeResources(context.Background(), nodeID, tunnels)
	}
	controlSrv.SetOnNodeDisconnect(disconnectHandler)

	// --- 节点管理器 + 健康检查 ---
	go node.StartHealthCheck(ctx, nodeMgr, disconnectHandler)

	// --- 接入 Token 认证服务 ---
	accessTokenRepo := storage.NewAccessTokenRepo(db)
	nodeAccessAuth := service.NewAccessTokenAuthService(accessTokenRepo, token)
	controlSrv.SetAuthenticator(nodeAccessAuth)

	// --- MQTT Broker ---
	var mqttBroker *mqtt.EmbeddedBroker
	if cfg.MQTT.Enabled {
		mqttBroker = mqtt.NewEmbeddedBroker(cfg.MQTT.TCPPort, cfg.MQTT.WSPort, authSvc, rbacEngine)
		go func() {
			slog.Info("MQTT broker starting...")
			if err := mqttBroker.Start(ctx); err != nil {
				slog.Error("MQTT broker error", "error", err)
				cancel()
			}
		}()
	}

	// --- 飞书集成 ---
	feishuClient := feishu.NewClient(cfg.Feishu.AppID, cfg.Feishu.AppSecret)
	feishuBindingRepo := storage.NewFeishuBindingRepo(db)

	// --- 钉钉集成 ---
	dingtalkClient := dingtalk.NewClient(cfg.DingTalk.AppKey, cfg.DingTalk.AppSecret, cfg.DingTalk.CorpID)
	dingtalkBindingRepo := storage.NewDingTalkBindingRepo(db)

	// --- HTTP API 服务（静态文件 + API） ---
	apiRouter := buildAPIRouter(authMW, apiLimiter, authSvc, nodeMgr, cfg, mqttBroker, gateway, controlSrv, userRepo, roleRepo, rbacEngine, nodeRepo, tunnelSvc, accessTokenRepo, feishuClient, feishuBindingRepo, dingtalkClient, dingtalkBindingRepo, jwtMgr, gatewayLimiter, tunnelEncryptor)
	adminDir, _ := os.Getwd()
	distDir := filepath.Join(adminDir, "admin", "dist")
	fileServer := http.FileServer(http.Dir(distDir))
	adminFS := http.StripPrefix("/admin", fileServer)
	mobileDistDir := filepath.Join(adminDir, "mobile", "dist")
	mobileFS := http.StripPrefix("/mobile", http.FileServer(http.Dir(mobileDistDir)))
	mobileIndexPath := filepath.Join(mobileDistDir, "index.html")
	indexPath := filepath.Join(distDir, "index.html")
	spaHandler := func(fs http.Handler, dist, index string) http.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) {
			prefix := r.URL.Path[:strings.Index(r.URL.Path[1:], "/")+1]
			staticPath := strings.TrimPrefix(r.URL.Path, prefix)
			if staticPath == "" {
				staticPath = "/"
			}
			fullPath := filepath.Join(dist, filepath.Clean(staticPath))
			if fi, err := os.Stat(fullPath); err == nil && !fi.IsDir() {
				fs.ServeHTTP(w, r)
				return
			}
			if strings.Contains(staticPath, ".") {
				http.NotFound(w, r)
				return
			}
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			html, _ := os.ReadFile(index)
			w.Write(html)
		}
	}
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/admin") {
			spaHandler(adminFS, distDir, indexPath).ServeHTTP(w, r)
			return
		}
		if strings.HasPrefix(r.URL.Path, "/mobile") {
			spaHandler(mobileFS, mobileDistDir, mobileIndexPath).ServeHTTP(w, r)
			return
		}
		apiRouter.ServeHTTP(w, r)
	})
	apiSrv := &http.Server{
		Addr:    cfg.Server.APIPort,
		Handler: handler,
	}
	go func() {
		slog.Info("API server listening", "addr", cfg.Server.APIPort)
		if err := apiSrv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("API server error", "error", err)
			cancel()
		}
	}()

	gatewaySrv := &http.Server{
		Addr:    cfg.Server.GatewayPort,
		Handler: gateway,
	}
	go func() {
		slog.Info("Gateway server listening", "addr", cfg.Server.GatewayPort)
		if err := gatewaySrv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("Gateway server error", "error", err)
			cancel()
		}
	}()

	slog.Info("moleAgent_Serv started",
		"controlPort", cfg.Server.ControlPort,
		"gatewayPort", cfg.Server.GatewayPort,
		"apiPort", cfg.Server.APIPort,
	)

	// 等待关闭信号
	<-ctx.Done()

	// 优雅关闭 HTTP 服务
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()
	apiSrv.Shutdown(shutdownCtx)
	gatewaySrv.Shutdown(shutdownCtx)
	if mqttBroker != nil {
		_ = mqttBroker.Stop(shutdownCtx)
	}
	gateway.Stop()
	if apiLimiter != nil {
		apiLimiter.Close()
	}

	slog.Info("moleAgent_Serv stopped gracefully")
}

func buildAPIRouter(
	mw *auth.AuthMiddleware,
	apiLimiter *ratelimit.APILimiter,
	authSvc *auth.AuthService,
	nodeMgr *node.ShardedNodeManager,
	cfg *config.Config,
	mqttBroker *mqtt.EmbeddedBroker,
	gateway *tunnel.TunnelGateway,
	controlSrv *tunnel.ControlServer,
	userRepo core.UserRepo,
	roleRepo core.RoleRepo,
	rbacEngine *auth.RBACEngine,
	nodeRepo core.NodeRepo,
	tunnelSvc *service.TunnelConfigService,
	accessTokenRepo core.AccessTokenRepo,
	feishuClient *feishu.Client,
	feishuBindingRepo core.FeishuBindingRepo,
	dingtalkClient *dingtalk.Client,
	dingtalkBindingRepo core.DingTalkBindingRepo,
	jwtMgr *auth.JWTManager,
	gatewayLimiter ratelimit.GatewayLimiter,
	tunnelEncryptor *crypto.SecretEncryptor,
) http.Handler {
	router := api.NewRouter(mw, apiLimiter)

	// Handlers
	authH := api.NewAuthHandler(authSvc)
	userH := api.NewUserHandler(userRepo, rbacEngine, cfg.Auth.BcryptCost, nodeRepo, accessTokenRepo, nodeMgr)
	roleH := api.NewRoleHandler(roleRepo)
	nodeH := api.NewNodeHandler(nodeMgr, nodeRepo, tunnelSvc, controlSrv)
	tunnelH := api.NewTunnelHandler(nodeMgr, tunnelSvc, gateway.Stats(), gatewayLimiter, tunnelEncryptor, controlSrv)
	mqttH := api.NewMQTTHandler(mqttBroker)
	sysH := api.NewSystemHandler(storage.DB(), cfg)
	tokenH := api.NewAccessTokenHandler(accessTokenRepo)
	feishuH := api.NewFeishuHandler(feishuClient, authSvc, feishuBindingRepo, userRepo, jwtMgr, rbacEngine, storage.DB())
	dingtalkH := api.NewDingTalkHandler(dingtalkClient, authSvc, dingtalkBindingRepo, userRepo, jwtMgr, rbacEngine, storage.DB())
	updateH := api.NewUpdateHandler()
	websshH := api.NewWebSSHHandler(nodeMgr)

	// === 公开端点 ===
	router.RegisterPublic("POST", "/api/v1/auth/login", authH.Login)
	router.RegisterPublic("GET", "/api/v1/health", sysH.Health)
	router.RegisterPublic("GET", "/api/v1/version", sysH.Version)
	router.RegisterPublic("POST", "/api/v1/auth/feishu/callback", feishuH.Callback)
	router.RegisterPublic("POST", "/api/v1/auth/feishu/bind", feishuH.Bind)
	router.RegisterPublic("GET", "/api/v1/auth/feishu/config", feishuH.Config)

	router.RegisterPublic("POST", "/api/v1/auth/dingtalk/callback", dingtalkH.Callback)
	router.RegisterPublic("POST", "/api/v1/auth/dingtalk/bind", dingtalkH.Bind)
	router.RegisterPublic("GET", "/api/v1/auth/dingtalk/config", dingtalkH.Config)

	// === 需要认证的端点 ===
	router.RegisterAuth("POST", "/api/v1/auth/logout", authH.Logout)
	router.RegisterAuth("POST", "/api/v1/auth/refresh", authH.Refresh)
	router.RegisterAuth("GET", "/api/v1/auth/me", authH.Me)
	router.RegisterAuth("POST", "/api/v1/auth/changepass", authH.ChangePass)

	// === 个人 Access Token 管理 ===
	router.RegisterAuth("GET", "/api/v1/me/access-tokens", tokenH.List)
	router.RegisterAuth("POST", "/api/v1/me/access-tokens", tokenH.Create)
	router.RegisterAuth("DELETE", "/api/v1/me/access-tokens/", tokenH.Delete)
	router.RegisterAuth("POST", "/api/v1/me/access-tokens/", tokenH.Rotate)

	// === 飞书绑定管理 ===
	router.RegisterAuth("GET", "/api/v1/me/feishu-bindings", feishuH.GetBinding)
	router.RegisterAuth("DELETE", "/api/v1/me/feishu-bindings", feishuH.Unbind)

	// === 钉钉绑定管理 ===
	router.RegisterAuth("GET", "/api/v1/me/dingtalk-bindings", dingtalkH.GetBinding)
	router.RegisterAuth("DELETE", "/api/v1/me/dingtalk-bindings", dingtalkH.Unbind)

	// === 用户管理（RBAC） ===
	router.Register("GET", "/api/v1/users", userH.List, "users", "read")
	router.Register("POST", "/api/v1/users", userH.Create, "users", "write")
	router.Register("GET", "/api/v1/users/", userH.Get, "users", "read")
	router.Register("PUT", "/api/v1/users/", userH.Update, "users", "write")
	router.Register("DELETE", "/api/v1/users/", userH.Delete, "users", "delete")
	router.Register("POST", "/api/v1/users/", userH.AssignRole, "users", "admin")

	// === 角色管理 ===
	router.Register("GET", "/api/v1/roles", roleH.List, "roles", "read")
	router.Register("POST", "/api/v1/roles", roleH.Create, "roles", "write")
	router.Register("GET", "/api/v1/roles/", roleH.Get, "roles", "read")
	router.Register("PUT", "/api/v1/roles/", roleH.Update, "roles", "write")
	router.Register("DELETE", "/api/v1/roles/", roleH.Delete, "roles", "delete")
	router.Register("GET", "/api/v1/permissions", roleH.ListPermissions, "roles", "read")

	// === 节点管理 ===
	router.Register("GET", "/api/v1/nodes", nodeH.List, "nodes", "read")
	router.Register("POST", "/api/v1/nodes", nodeH.Create, "nodes", "write")
	router.Register("GET", "/api/v1/nodes/persisted", nodeH.ListPersisted, "nodes", "read")
	router.Register("GET", "/api/v1/nodes/", nodeH.Get, "nodes", "read")
	router.Register("PUT", "/api/v1/nodes/", nodeH.Update, "nodes", "write")
	router.Register("DELETE", "/api/v1/nodes/", nodeH.Delete, "nodes", "delete")
	router.Register("PATCH", "/api/v1/nodes/", nodeH.UpdateRateLimit, "nodes", "write")
	router.Register("POST", "/api/v1/nodes/", nodeH.Restart, "nodes", "admin")

	// === 隧道管理 ===
	router.Register("GET", "/api/v1/tunnels", tunnelH.List, "tunnels", "read")
	router.Register("GET", "/api/v1/tunnels/stats", tunnelH.Stats, "tunnels", "read")
	router.Register("GET", "/api/v1/tunnels/usage", tunnelH.Usage, "tunnels", "read")
	router.Register("POST", "/api/v1/tunnels", tunnelH.Create, "tunnels", "write")
	router.Register("PATCH", "/api/v1/tunnels/rate-limit", tunnelH.BatchRateLimit, "tunnels", "write")
	router.Register("DELETE", "/api/v1/tunnels/", tunnelH.Delete, "tunnels", "delete")
	router.Register("POST", "/api/v1/tunnels/", tunnelH.Action, "tunnels", "admin")

	// === MQTT 管理 ===
	router.Register("GET", "/api/v1/mqtt/clients", mqttH.Clients, "mqtt", "read")
	router.Register("GET", "/api/v1/mqtt/topics", mqttH.Topics, "mqtt", "read")
	router.Register("GET", "/api/v1/mqtt/stats", mqttH.Stats, "mqtt", "read")
	router.Register("POST", "/api/v1/mqtt/publish", mqttH.Publish, "mqtt", "write")
	router.Register("GET", "/api/v1/mqtt/health", mqttH.Health, "mqtt", "read")

	// === 系统管理 ===
	router.Register("GET", "/api/v1/metrics", sysH.Metrics, "system", "read")
	router.Register("GET", "/api/v1/config", sysH.GetConfig, "system", "admin")
	router.Register("GET", "/api/v1/accesskey", sysH.GetAccessKey, "accesskey", "read")
	router.Register("PUT", "/api/v1/accesskey", sysH.SetAccessKey, "accesskey", "admin")
	router.Register("DELETE", "/api/v1/accesskey", sysH.DeleteAccessKey, "accesskey", "admin")

	// === 版本升级 ===
	router.Register("GET", "/api/v1/check-update", updateH.CheckUpdate, "system", "read")
	router.Register("POST", "/api/v1/self-update", updateH.SelfUpdate, "system", "admin")
	router.Register("GET", "/api/v1/update-progress", updateH.UpdateProgress, "system", "read")

	// === WebSSH 终端 ===
	router.RegisterAuth("GET", "/api/v1/tunnels/", websshH.Handle)

	return router.Build()
}

func parseExpiry(s string) time.Duration {
	d, err := time.ParseDuration(s)
	if err != nil {
		return 24 * time.Hour
	}
	return d
}
