// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function CheckNodeStatus(arg1) {
  return window['go']['main']['App']['CheckNodeStatus'](arg1);
}

export function GetAllNodeStatus() {
  return window['go']['main']['App']['GetAllNodeStatus']();
}

export function GetCurrentNode() {
  return window['go']['main']['App']['GetCurrentNode']();
}

export function GetCurrentNodeURL() {
  return window['go']['main']['App']['GetCurrentNodeURL']();
}

export function GetShellInfo() {
  return window['go']['main']['App']['GetShellInfo']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function RequestActivate() {
  return window['go']['main']['App']['RequestActivate']();
}

export function SwitchNode(arg1) {
  return window['go']['main']['App']['SwitchNode'](arg1);
}

export function UpdateNode(arg1, arg2) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2);
}
