// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1:string):Promise<string>;

export function CheckNodeStatus(arg1:string):Promise<string>;

export function GetAllNodeStatus():Promise<string>;

export function GetCurrentNode():Promise<string>;

export function GetCurrentNodeURL():Promise<string>;

export function GetShellInfo():Promise<string>;

export function ListNodes():Promise<string>;

export function RemoveNode(arg1:string):Promise<string>;

export function RequestActivate():Promise<void>;

export function SwitchNode(arg1:string):Promise<string>;

export function UpdateNode(arg1:string,arg2:string):Promise<string>;
