// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function GetAllTunnelStatus() {
  return window['go']['main']['App']['GetAllTunnelStatus']();
}

export function GetBuiltinHTTPBaseURL() {
  return window['go']['main']['App']['GetBuiltinHTTPBaseURL']();
}

export function GetBuiltinHTTPPort() {
  return window['go']['main']['App']['GetBuiltinHTTPPort']();
}

export function GetCurrentNode() {
  return window['go']['main']['App']['GetCurrentNode']();
}

export function GetSer2MQStatus(arg1) {
  return window['go']['main']['App']['GetSer2MQStatus'](arg1);
}

export function GetShellInfo() {
  return window['go']['main']['App']['GetShellInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVPNStatus(arg1) {
  return window['go']['main']['App']['GetVPNStatus'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function RemoveTunnel(arg1) {
  return window['go']['main']['App']['RemoveTunnel'](arg1);
}

export function RequestActivate() {
  return window['go']['main']['App']['RequestActivate']();
}

export function SetBuiltinHTTPPort(arg1) {
  return window['go']['main']['App']['SetBuiltinHTTPPort'](arg1);
}

export function SwitchNode(arg1) {
  return window['go']['main']['App']['SwitchNode'](arg1);
}

export function SwitchToNode(arg1) {
  return window['go']['main']['App']['SwitchToNode'](arg1);
}

export function UpdateNode(arg1, arg2) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2);
}

export function VPNStart(arg1) {
  return window['go']['main']['App']['VPNStart'](arg1);
}

export function VPNStop(arg1) {
  return window['go']['main']['App']['VPNStop'](arg1);
}
