// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1:string):Promise<string>;

export function AddTunnel(arg1:string):Promise<string>;

export function GetAllTunnelStatus():Promise<string>;

export function GetBuiltinHTTPBaseURL():Promise<string>;

export function GetBuiltinHTTPPort():Promise<string>;

export function GetCurrentNode():Promise<string>;

export function GetSer2MQStatus(arg1:string):Promise<string>;

export function GetShellInfo():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function GetVPNStatus(arg1:string):Promise<string>;

export function GetVersion():Promise<Record<string, string>>;

export function ListNodes():Promise<string>;

export function RemoveNode(arg1:string):Promise<string>;

export function RemoveTunnel(arg1:string):Promise<string>;

export function RequestActivate():Promise<void>;

export function SetBuiltinHTTPPort(arg1:string):Promise<void>;

export function SwitchNode(arg1:string):Promise<string>;

export function SwitchToNode(arg1:string):Promise<void>;

export function UpdateNode(arg1:string,arg2:string):Promise<string>;

export function VPNStart(arg1:string):Promise<string>;

export function VPNStop(arg1:string):Promise<string>;
